backend/moduls/user/controllers/DefaultController.php
<?php

namespace app\moduls\user\controllers;

use app\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

/**
 * Default controller for the `user` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index page for the module
     * @return string
     */
    public function actionIndex()
    {
        $session = Yii::$app->session;
        $sp = unserialize($session['spCalls']);
        $query = User::find();
        if (is_array($sp)){
            foreach (@$sp as $key=>$value){
                if (strlen($value)) $query->andWhere(['like', $key, $value]);
            }
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'key' => 'id',
            'pagination' => [
                'pageSize' => 50,
            ],
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'params' => Yii::$app->params,
            'translations' => Yii::$app->translations,
        ]);
    }
    /**
     * Renders the view page for the module
     * @return string
     */
    public function actionView()
    {
        $user = new User;
        if (array_key_exists('id',$_REQUEST)){
            $user = User::find()->where(['id'=>$_REQUEST['id']])->one();
        }

        return $this->render('view',
            [
                'user'=>$user,
            ]
        );
    }
    /**
     * Renders the edit page for the module
     * @return string
     */
    public function actionEdit()
    {
        $get = Yii::$app->request->get();
        if(array_key_exists('id', $get) && $get['id'] != '') {
            $model = User::findOne($get['id']);
        } else {
            $model = new User;
        }

        if(!strlen($model->id)) {
            $return_action = 'index';
        } else {
            $return_action = 'view/?id=' . $model->id;
        }

        return $this->render('edit',[
            'user' => $model,
            'return_action' => $return_action,
        ]);
    }
    /**
     * Renders the update page for the module
     * @return string
     */
    public function actionUpdate()
    {
        $get = Yii::$app->request->get();
        if(array_key_exists('id', $get) && $get['id'] != '') {
            $model = User::findOne($get['id']);
        } else {
            $model = new User;
        }

        if(!strlen($model->id)) {
            $return_action = 'index';
        } else {
            $return_action = 'view/?id=' . $model->id;
        }

        return $this->render('edit',[
            'user' => $model,
            'return_action' => $return_action,
        ]);
    }
    /**
     * Save action for app\models\User model
     * @return string
     */
    public function actionSave()
    {
        $post = Yii::$app->request->post();
        if ($post && $post['id'] != '') {
            $model = User::findOne($post['id']);
            $model->updated_at = time();
        } else {
            $model = new User;
            $model->created_at = time();
            $model->updated_at = 0;
            $model->auth_key = '1';
            $model->password_reset_token = '1';
            //$model->status = 10;
            //$model->role = 0;
        }

        if($post['user']['password'] != '') {
            $model->password_hash = password_hash($post['user']['password'], PASSWORD_DEFAULT);
        }

        $model->username = $post['user']['username'];
        $model->email = $post['user']['email'];
        $model->user_activity = $post['user']['status'];
        $model->status = $post['user']['status'];
        $model->extension = $post['user']['extension'];
        $model->telephony_server = $post['user']['telephony_server'];
        $model->last_name =  $post['user']['last_name'];
        $model->middle_name = $post['user']['middle_name'];
        $model->first_name =  $post['user']['first_name'];
        $model->first_name =  $post['user']['first_name'];
        $model->role = $post['user']['role'];
        $model->is_admin = $post['user']['is_admin'];
        $model->save();
        $erros = [];
        if(is_array($model->errors)) {
            foreach ($model->errors as $key => $value){
                $erros[$key] = $value[0]."\n";
            }
        }

        if(!count($erros)) {
            $return = [
                'key' => $model->id,
                'erros' => '0',
            ];
        } else {
            $return = $erros;
        }
        return json_encode($return);
    }
    /**
     * Delete row action for app\models\User model
     * @return void
     */
    public function actionDelete(){
        $get = Yii::$app->request->get();
        if (array_key_exists('id', $get) && $get['id'] != ''){
            $model = User::find()->where(['id' => $get['id']])->one();
            if ($model->id!=1){
                $model->delete();
            }

        }
    }
    /**
     * @return void
     */
    public function actionActivity(){

        if (array_key_exists('id',$_REQUEST)){
            $model = User::find()->where(['id'=>$_REQUEST['id']])->one();
            if ($model->user_activity =='1' && $model->id!=1){
                $model->user_activity ='0';
                $model->status ='0';
            }else{
                $model->user_activity = '1';
                $model->status ='10';
            }
            $model->save();
        }
    }
    /**
     * @inheritdoc
     */
    public function actionSearch()
    {
        $session = \Yii::$app->session;
        $session['spUser'] = serialize($_REQUEST['user']);
    }

    public function actionChpassword()
    {
        $model = User::find()->where(['id' => $_REQUEST['id']])->one();
        $erros = [];
        if ($_REQUEST['user']['password'] != '' && Yii::$app->user->identity->is_admin) {
            $model->password_hash = password_hash($_REQUEST['user']['password'], PASSWORD_DEFAULT);
            $model->save();
        }elseif (Yii::$app->user->id == $model->id){
            $model->password_hash = password_hash($_REQUEST['user']['password'], PASSWORD_DEFAULT);
            $model->save();
        }else{
            $erros['password_new'] = Yii::$app->translations['password is required']."\n";
        }

        if(!count($erros)) {
            $return = [
                'key' => $model->id,
                'erros' => '0',
            ];
        } else {
            $return = $erros;
        }
        return json_encode($return);
    }

    public function actionSearchclear()
    {
        $session = \Yii::$app->session;
        $session['spUser'] = '';
    }

}

backend/moduls/user/views/default/edit.php
<?php
/*
 * user
 *
 */

use yii\helpers\Url;
use yii\widgets\Pjax;
use backend\extension\pbxUrlReturn;

/*
 * названия модуля
 */
$modulName = 'user';

/*
 * url для возврата к форме на которую нужно вернутся
 */
$returnUrl = pbxUrlReturn::getUrl();

?>
<script>
    $(function () {
        $('#user_edit').submit(function (e) {
            var $form = $(this);
            $.ajax({
                type: $form.attr('method'),
                url: $form.attr('action'),
                data: $form.serialize(),
                dataType: 'json'
            }).done(function (json) {
                if (json.erros == 0) {
                    go('<?= Url::toRoute($returnUrl);?>');
                }

                $('.uk-alert-danger').html('');
                $('.uk-alert-danger').css('display','none');
                console.log(json);
                for (var item in json) {
                    errors(item, json[item]);
                }
            }).fail(function () {
                console.log('fail');
            });
            e.preventDefault();
        });
        function errors(fieldId, erorsValue) {
            $('#alert-danger-' + fieldId).html(erorsValue);
            $('#alert-danger-' + fieldId).css('display','block');
        }
    });
</script>
<div class="uk-card uk-card-default panel-num-1">
<form id="user_edit" action="<?= Url::toRoute('/user/default/save');?>" method="post">
    <input name="id" type="hidden" value="<?= @$user->id; ?>">
    <input id="form-token" type="hidden" name="<?= \Yii::$app->request->csrfParam ?>"
           value="<?= \Yii::$app->request->csrfToken ?>"/>
    <?= Yii::$app->controller->renderPartial('@app/templates/breadcrumb/default', ['modul'=>$modulName,'id'=>@$user->id]);?>
    <?= Yii::$app->controller->renderPartial('@app/templates/action/edit', ['return_action' => @$returnUrl]); ?>
    <div class="uk-grid-match uk-child-width-expand@s uk-text-center uk-flex-center">
        <div uk-filter="target: .js-filter" style="overflow: hidden">
            <script>
                $(document).ready(function () {
                    $('.js-filter').removeAttr( 'style' );
                });
            </script>
            <div class="uk-grid-small uk-grid-divider uk-child-width-auto" uk-grid>
                <div>
                    <ul class="uk-subnav uk-subnav-pill" uk-margin>
                        <li class="uk-active" class="uk-active" uk-filter-control="[data-tags*='main-fields']">
                            <a href="#"><?= Yii::$app->translations['main-fields']; ?></a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul class="uk-subnav uk-subnav-pill" uk-margin>
                        <li uk-filter-control="[data-tags*='required-fields']">
                            <a href="#"><?= Yii::$app->translations['required-fields']; ?>
                                <span class="uk-label uk-label-danger">( * )</span></a>
                        </li>
                        <li uk-filter-control>
                            <a href="#"><?= Yii::$app->translations['all-filds']; ?></a>
                        </li>
                    </ul>
                </div>
            </div>

            <ul class="js-filter uk-child-width-1-1 uk-child-width-1-2@m uk-text-center" uk-grid="masonry: true">
                <li data-tags="required-fields main-fields" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'username',
                            'name' => 'user[username]',
                            'value' => @$user->username,
                            'placeholder' => '',
                            'required'=>1,
                            'lable' => Yii::$app->translations['username'],
                            'error' => @$model->errors['username']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all-filds" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'extension',
                            'name' => 'user[extension]',
                            'value' => @$user->extension,
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['extension'],
                            'error' => @$model->errors['extension']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="<?if(!is_int(@$user->id))echo 'required-fields';?> main-fields" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable-generator-password', [
                            'id' => 'password_hash',
                            'name' => 'user[password]',
                            'value' => '',
                            'placeholder' => '',
                            'required'=>!is_int(@$user->id),
                            'lable' => Yii::$app->translations['password'],
                            'error' => @$model->errors['password']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all-filds main-fields" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'first_name',
                            'name' => 'user[first_name]',
                            'value' => @$user->first_name,
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['first_name'],
                            'error' => @$model->errors['first_name']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="required-fields main-fields" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'last_name',
                            'name' => 'user[last_name]',
                            'value' => @$user->last_name,
                            'placeholder' => '',
                            'required'=>1,
                            'lable' => Yii::$app->translations['last_name'],
                            'error' => @$model->errors['last_name']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all-filds" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'middle_name',
                            'name' => 'user[middle_name]',
                            'value' => @$user->middle_name,
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['middle_name'],
                            'error' => @$model->errors['middle_name']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all-filds" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'email',
                            'name' => 'user[email]',
                            'value' => @$user->email,
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['email'],
                            'error' => @$model->errors['email']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="required-fields main-fields" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/select-lable', [
                            'id' => 'status',
                            'name' => 'user[status]',
                            'required'=>1,
                            'value' => @$user->user_activity,
                            'lable' => Yii::$app->translations['user_activity'],
                            'error' => @$model->errors['status'],
                            'option' => Yii::$app->translations['cb_user_status'],
                        ]
                    );
                    ?>
                </li>
                <li data-tags="required-fields main-fields" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/popup-lable-select', [
                            'id' => 'role',
                            'name' => 'user[role]',
                            'placeholder' => '',
                            'required' => 1,
                            'lable' => Yii::$app->translations['role'],
                            'openAction'=>'/role/default/select',
                            'model'=>app\models\Role::findOne(@$user->role),
                            'atrName'=>'role_name',
                            'atrID'=>'role_id',
                        ]
                    );
                    ?>
                </li>
                <li data-tags="required-fields main-fields" data-size="medium" style="margin-top: 0;">
                    <?php
                    foreach (Yii::$app->params['api_ats_config'] as $key => $value) {
                        $pbx[$key] = Yii::$app->translations[$key];
                    }
                    echo Yii::$app->controller->renderPartial('@app/templates/form/select-lable', [
                            'id' => 'telephony_server',
                            'name' => 'user[telephony_server]',
                            'value' => @$user->telephony_server,
                            'required'=>1,
                            'lable' => Yii::$app->translations['telephony_server'],
                            'error' => @$model->errors['telephony_server'],
                            'option' => $pbx,
                        ]
                    );
                    ?>
                </li>
                <li data-tags="required-fields main-fields" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/select-lable', [
                            'id' => 'is_admin',
                            'name' => 'user[is_admin]',
                            'required'=>0,
                            'value' => @$user->is_admin,
                            'lable' => Yii::$app->translations['is_admin'],
                            'error' => @$model->errors['is_admin'],
                            'option' => Yii::$app->translations['cb_is_admin'],
                        ]
                    );
                    ?>
                </li>
            </ul>
        </div>
    </div>
    <?= Yii::$app->controller->renderPartial('@app/templates/action/edit', ['return_action' => @$returnUrl]); ?>
</form>
</div>

backend/moduls/user/views/default/index.php
<?php

use app\models\User;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;

$modulName = 'user';
$session = \Yii::$app->session;
if (strlen($session['spUser'])) {
    $search = unserialize($session['spUser']);
} else {
    $search = array();
};
$params = \Yii::$app->params;
?>
<div class="block-interface z-depth-1">
    <form id="<?= $modulName ?>-search" action="<?php echo Url::toRoute('/' . $modulName . '/default/search'); ?>"
          method="post">
        <input id="form-token" type="hidden" name="<?= \Yii::$app->request->csrfParam ?>"/>
        <div class="modul-card-badge modul-label"><?= Yii::$app->translations[$modulName]; ?></div>
        <div uk-filter="target: .js-filter" style="overflow: hidden;padding-right: 8px;">

            <div class="uk-grid-small uk-grid-divider uk-child-width-auto" uk-grid>
                <div>
                    <ul class="uk-subnav uk-subnav-pill" uk-margin>
                        <li class="uk-active" uk-filter-control="[data-tags='main']">
                            <a href="#" class="uk-active"><?= Yii::$app->translations['main']; ?></a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul class="uk-subnav uk-subnav-pill" uk-margin>
                        <li uk-filter-control><a href="#"><?= Yii::$app->translations['all']; ?></a></li>
                    </ul>
                </div>
            </div>
            <ul class="js-filter uk-child-width-1-2 uk-child-width-1-3@m uk-text-center" uk-grid="masonry: true">
                <script>
                    $(document).ready(function () {
                        $('.js-filter').removeAttr( 'style' );
                    });
                </script>
                <li data-tags="main" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'username',
                            'name' => 'user[username]',
                            'value' => @$search['username'],
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['username'],
                            'error' => @$model->errors['username']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="main" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'role',
                            'name' => 'user[role]',
                            'value' => @$search['role'],
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['role'],
                            'error' => @$model->errors['role']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'first_name',
                            'name' => 'user[first_name]',
                            'value' => @$search['first_name'],
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['first_name'],
                            'error' => @$model->errors['first_name']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="main" class="ls-search-form" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'last_name',
                            'name' => 'user[last_name]',
                            'value' => @$search['last_name'],
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['last_name'],
                            'error' => @$model->errors['last_name']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'middle_name',
                            'name' => 'user[middle_name]',
                            'value' => @$search['middle_name'],
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['middle_name'],
                            'error' => @$model->errors['middle_name']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/input-lable', [
                            'id' => 'email',
                            'name' => 'user[email]',
                            'value' => @$search['email'],
                            'placeholder' => '',
                            'lable' => Yii::$app->translations['email'],
                            'error' => @$model->errors['email']
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/select-lable', [
                            'id' => 'status',
                            'name' => 'user[status]',
                            'value' => @$search['status'],
                            'lable' => Yii::$app->translations['status'],
                            'error' => @$model->errors['status'],
                            'option' => Yii::$app->translations['cb_user_status'],
                        ]
                    );
                    ?>
                </li>
                <li data-tags="all" data-size="medium" style="margin-top: 0;">
                    <?= Yii::$app->controller->renderPartial('@app/templates/form/select-lable', [
                            'id' => 'user_type',
                            'name' => 'user[user_type]',
                            'value' => @$search['user_type'],
                            'lable' => Yii::$app->translations['user_type'],
                            'error' => @$model->errors['user_type'],
                            'option' => Yii::$app->translations['cb_user_type'],
                        ]
                    );
                    ?>
                </li>
            </ul>
            <div class="btn-group" style="padding: 10px 10px 10px 0;">
                <a type="submit" href="/<?= $modulName; ?>/default/update" class="btn btn-success">
                    <?= \Yii::$app->translations['create'] ?>
                </a>
            </div>
            <div class="btn-group" style="float: right;padding: 10px">
                <button type="button" onclick="clear_search();"
                        class="btn btn-primary"><?= Yii::$app->translations['clear']; ?></button>
                <button type="submit" class="btn btn-success"><?= \Yii::$app->translations['find']; ?></button>
            </div>
        </div>
    </form>

    <?php
    $query = User::find();
    if (is_array($search)) {
        foreach (@$search as $key => $value) {
            if ($key == 'status' && strlen($value)) {
                $query->andWhere(['=', $key, $value]);
            } elseif (strlen($value)) {
                $query->andWhere(['like', $key, $value]);
            }

        }
    }

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'key' => 'id',
        'pagination' => [
            'pageSize' => 50,
        ],
    ]);

    Pjax::begin(['id' => $modulName . 'pjax', 'timeout' => 5000, 'enablePushState' => true, 'clientOptions' => ['method' => 'POST']]);
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'id' => 'list_' . $modulName,
        'columns' => [
            'username',
            'first_name',
            'last_name',
            'list_ations' => array(
                'format' => 'raw',
                'options' => [
                    'style' => 'width: 150px;',
                ],
                'value' => function ($data) {
                    return Yii::$app->controller->renderPartial('@app/templates/list_actions/index',
                        array('data' => $data,
                            'modul' => 'user',
                            'controller' => 'default',
                            'key' => 'id',
                            'id' => 'user',
                            'options' => array(),
                        )
                    );
                }
            ),
        ],
    ]);
    Pjax::end();
    ?>
    <script type="text/javascript">

        function reload_<?=$modulName;?>_list() {
            jQuery.pjax.defaults.timeout = 5000;
            jQuery.pjax.reload({container: '#<?=$modulName;?>pjax'});
        }

        function delete_<?=$modulName;?>(id) {
            $.ajax({
                type: 'get',
                url: "<?php echo Url::toRoute('/' . $modulName . '/default/delete');?>",
                data: 'id=' + id
            }).done(function (data) {
                reload_<?=$modulName;?>_list();
                console.log(data);
            }).fail(function () {
                console.log('fail');
            });
        }

        function activity_<?=$modulName;?>(id) {
            $.ajax({
                type: 'get',
                url: "<?php echo Url::toRoute('/' . $modulName . '/default/activity');?>",
                data: 'id=' + id
            }).done(function (data) {
                reload_<?=$modulName;?>_list();
                console.log(data);
            }).fail(function () {
                console.log('fail');
            });
        }


        function searchClear_groups_list() {
            $('.search-field').val('');
        }


        $(function () {
            $('#<?=$modulName?>-search').submit(function (e) {
                var $form = $(this);
                $.ajax({
                    type: $form.attr('method'),
                    url: $form.attr('action'),
                    data: $form.serialize()
                }).done(function (data) {
                    reload_<?=$modulName;?>_list();
                    console.log(data);
                }).fail(function () {
                    console.log('fail');
                });
                e.preventDefault();
            });
        });


        function clear_search() {
            $('.uk-select').val('');
            $('.uk-input').val('');
            $.ajax({
                type: 'get',
                url: "<?php echo Url::toRoute('/' . $modulName . '/default/searchclear');?>",
                data: 'id='
            }).done(function (data) {
                reload_<?=$modulName;?>_list();
                console.log(data);
            }).fail(function () {
                console.log('fail');
            });
        }
    </script>